// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class FirewallResources
{
        public const string achievement_sequenceprocess10 = "CgkIqO6pv6ofEAIQBg"; // <GPGSID>
        public const string achievement_initializesystemprotectiontrue = "CgkIqO6pv6ofEAIQAw"; // <GPGSID>
        public const string achievement_firewallruntimems900000 = "CgkIqO6pv6ofEAIQCA"; // <GPGSID>
        public const string leaderboard_high_scores = "CgkIqO6pv6ofEAIQDQ"; // <GPGSID>
        public const string achievement_creditsinitiatedtrue = "CgkIqO6pv6ofEAIQDA"; // <GPGSID>
        public const string achievement_trainingcompletetrue = "CgkIqO6pv6ofEAIQBA"; // <GPGSID>
        public const string achievement_securityrank500 = "CgkIqO6pv6ofEAIQCw"; // <GPGSID>
        public const string achievement_securityrank1000 = "CgkIqO6pv6ofEAIQBQ"; // <GPGSID>
        public const string achievement_securityrank100 = "CgkIqO6pv6ofEAIQCg"; // <GPGSID>
        public const string achievement_firewallruntimems120000 = "CgkIqO6pv6ofEAIQCQ"; // <GPGSID>
        public const string achievement_sequenceprocess20 = "CgkIqO6pv6ofEAIQBw"; // <GPGSID>

}

